---
title: "Tidy data and relational datasets"
output: github_document
---

This document will show how to tidy data

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


## PIVOT LONGER

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

This needs to go from wide to long format

```{r}
pulse_tidy_df =
  pulse_df %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_" #strips off this piece automatically
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) %>% 
  relocate(id, visit) # reorders the columns
```

Just put it all together like this:

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_" #strips off this piece automatically
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) %>% 
  relocate(id, visit) # reorders the columns
```

Do one more example:

* pivot gestational weight for day 0 and 18
* recode through case_match

```{r}
litters_df =
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) %>% 
  mutate(
    gd_time = case_match(
      gd_time,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```
## PIVOT WIDER

Let's make up an analysis result table

```{r}
analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```

Pivot wider for human readability

```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) %>% 
  knitr::kable() # neat table
```


