---
title: "Data Import"
output: github_document
---

September 17 Lecture: This document will show how to import data.

```{r setup, echo= FALSE, message = FALSE}
library(tidyverse)
# can do library(janitor) and then just do clean_names, but it's only one function that we actually need so don't want to load the entire package.
library(readxl)
library(haven)
```

Import FAS Litters CSV:

```{r}
litters_df = read_csv("data/FAS_litters.csv")

#overwrite litters dataframe with better column names - use janitor function:

#clean names makes it snake case, replaces spaces, etc
litters_df = janitor::clean_names(litters_df)


```

```{r}
litters_df

head(litters_df)
tail(litters_df, 10)
```

```{r eval=FALSE}
view(litters_df)

```

Read in FAS Pups Dataset

```{r}
pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)

pups_df
```


Use absolute path: Don't use this because it doesn't account changing around things
```{r, eval=FALSE}
pups_df_ab = read_csv("~/Documents/fall 2024/p8105/lectures/data_wrangling_i/data/FAS_pups.csv")
```

Playing around with read_csv() parameters:
```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    #col_names = FALSE,
    #skip = 1, #skip lines
    na = c("NA", "", ".") #list things that should be considered as a missing value
  )

litters_df = janitor::clean_names(litters_df)

pull(litters_df, gd0_weight)
```

What if we code `group` as a character variable?

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA", "", "."),
    col_types = cols(
      Group = col_factor()
    )
  )

litters_df
```

Importing from Excel:

```{r excel_import}
# can specify sheets and ranges as well
mlb_df = read_excel("data/mlb11.xlsx")

mlb_df
```


Importing from SAS:
```{r sas_import}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")

pulse_df
```




