---
title: "Data Manipulation"
output: github_document
---

September 19 Lecture: This document will show how to manipulate data.

```{r setup, echo= FALSE, message = FALSE}
library(tidyverse)
```


```{r}
litters_df = 
  read.csv("data/FAS_litters.csv", na=c("NA", ".", ""))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na=c("NA", ".", ""))

pups_df = janitor::clean_names(pups_df)
```
## 'select' 

Use 'select()' to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group:gd18_weight)

select(litters_df, -pups_survive)

select(litters_df, -(group:gd18_weight))

select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))

select(litters_df, GROUP=group)

rename(litters_df, GROUP=group)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```


## `filter`

use ==, >=, <=, >, <, !=

```{r}
filter(litters_df, gd_of_birth == 20)

filter(litters_df, pups_born_alive > 5)

filter(litters_df, group=="Low8")
filter(litters_df, group %in% c("Low8", "Low7"))
filter(litters_df, group %in% c("Low8", "Low7"), pups_born_alive == 8)
```

```{r}
drop_na(litters_df) # drop any row that has any missing data

drop_na(litters_df, gd0_weight)
```


```{r}
filter(pups_df, sex==1)

filter(pups_df, pd_walk < 11, sex ==2)
```


